os: osx
language: objective-c
compiler: gcc
osx_image: xcode12

install:
  - export CI=false 
  - gcc -v  
  - brew install autoconf automake libtool berkeley-db4 pkg-config openssl boost boost-build libevent gettext texinfo
  - aclocal --print-ac-dir
  - export PATH="/usr/local/opt/texinfo/bin:$PATH"
  - ./autogen.sh
  - ./configure
  - make 
  - make install
  - nano -V
  - exit 0
  
