os: osx

install:
  - export CI=false 
  - printf "\e[33;1m%s\n" 'nano -V'
  - nano -V
  - gcc -v  
  - brew install berkeley-db4 texinfo
  - aclocal --print-ac-dir
  - export PATH="/usr/local/opt/texinfo/bin:$PATH"

script:
  - printf "\e[33;1m%s\n" 'Execute exit 0'
  - ./autogen.sh
  - ./configure
  - printf "\e[33;1m%s\n" 'Make'
  - make
  - printf "\e[33;1m%s\n" 'Install'
  - make install
  - nano -V
  - exit 0
