os: osx

install:
  - export CI=false 
  - printf "\e[33;1m%s\n" 'nano -V'
  - nano -V
  - printf "\e[33;1m%s\n" 'Install homebrew'
  - /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  - gcc -v  
  - brew install autoconf automake libtool berkeley-db4 pkg-config openssl boost boost-build libevent gettext texinfo
  - aclocal --print-ac-dir
  - export PATH="/usr/local/opt/texinfo/bin:$PATH"


deploy:
  provider: script
  script:
    - printf "\e[33;1m%s\n" 'Execute autogen'
    - ./autogen.sh
    - ./configure
    - printf "\e[33;1m%s\n" 'Make'
    - make 
    - printf "\e[33;1m%s\n" 'Install'
    - make install
    - nano -V
