os: osx

install:
  - echo "trigger 1"
  - gcc -v  
  - brew install autoconf automake libtool berkeley-db4 pkg-config openssl boost boost-build libevent gettext makeinfo texinfo
  - aclocal --print-ac-dir
  - export PATH="/usr/local/opt/texinfo/bin:$PATH"
  - ./autogen.sh
  - ./configure
  - make 
  - make install
  - nano -V
